#!/bin/bash

IPADDR=`hostname -I`
LASTIP=`echo $IPADDR | cut -c 1`
echo $LASTIP
NUMIP=${IPADDR##$LASTIP*.}
ENDIP=${IPADDR%$NUMIP}
echo $ENDIP
 
num=1
until [ $num -gt 255 ]
	do
	modifiedIP="$ENDIP$num"
	if ping -c 1 -W 1 "$modifiedIP" > /dev/null 2>&1; then 
	echo "$modifiedIP : alive"
	host=`host $modifiedIP | cut -d' ' -f5`
	echo "host : $host"
	extractedFile=`grep $modifiedIP /proc/net/arp`
	MACfile=`echo $extractedFile | cut -d' ' -f4`
        echo MAC : $MACfile
        if nc -v -w1 $modifiedIP 22 > /dev/null 2>&1; then 
	echo "Port 22: Successful!"
	else
	echo "Port 22: Failure"
	fi
	if nc -v -w1 $modifiedIP 80 > /dev/null 2>&1; then 
	echo "Port 80: Successful!"
	else
	echo "Port 80: Failure"
	fi
        echo " "
	fi
	((num++))
	
done

