#!/bin/bash
echo "What rpi would you like to ping?"
read varrpi
if [ "$varrpi" == "" ];then
for i in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20
do
        ping -c 1 -W 1 "rpi$i"  > /dev/null 2>&1;
        if [ $? -eq 0 ]; then
           echo "rpi$i : alive"
        else
           echo "rpi$i : dead"
        fi
done

else
	ping -c 1 -W 1 "$varrpi"  > /dev/null 2>&1;
	if [ $? -eq 0 ]; then
	   echo "$varrpi : alive"
	else
	   echo "$varrpi : dead"
	fi
fi














