#!/bin/bash

echo "Which Pi would you like to check?"
read input

if [ "$input" == "" ]; then
	for i in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20
	do 
		if ping -c 1 -W 1 "rpi$i" > /dev/null 2>&1; then 
			echo "rpi$i : alive"
		else
			echo "rpi$i : dead"
		fi
	done
else 
	  if ping -c 1 -W 1 "rpi$i" > /dev/null 2>&1; then 
                        echo "rpi$i : alive"
                else
                        echo "rpi$i : dead"
                fi
fi





			
